### PR TITLE
[Close #24] Enhancement/error pages

### LINKED ISSUE #24: 404 errors still with default rails page and don't follow site theme.

### PR DESCRIPTION
**Pull request by edmilsonefs**

### CODE REVIEW

**Comment by hugopl** [comment]
Did you test it? Because it doesn't work here, mainly because on application_controller we have code like this:

```
  rescue_from ActiveRecord::RecordNotFound do |_exception|
    render file: "#{Rails.root}/public/404", layout: false, status: :not_found
  end
```

**Comment by edmilsonefs** [comment]
For sure I tested, I will take a look again, maybe something else happened.

**Comment by edmilsonefs** [comment]
Regarding the code you mentioned above, I realized that I was behind your master branch by one commit. This is why I didn't noticed the code you pasted above. 

I also noticed that this code doesn't affect the application when I'm using my changes to display the custom error messages introduced, hence I removed it.

Note: With the change that was explained below you should be able to test these custom error messages on your development environment. For production this flag is false by default, if with that you still not able to see the proper error messages in production please give me more details on how you are doing it so I can reproduce by myself and try to figure out what's going on. *(I hope this is a configuration issue)*

**To be able to test these changes in your development environment you should change the following configuration**:

---

To open the file:
```
vim config/environment/development.rb +13
```

Do the proper change:

screenshot_033015_090649_am

Start the rails server again:
```
rails server
```

**Below is what you should expect to get with these changes**:

---
reviewit_evidence_error-pages

**Comment by hugopl** [comment]
I just squashed all commits in your branch, rebased then applied another commit on top of it fixing a issue when the user isn't logged in and simplifying some things.

Your commits squashed in a single one: a9d14aed9bc8b16f34a8c054ebd737f95682e31d
My changes: 379867a43821155b79979695432cd085317986ea

Thanks.

**Pull request closed without merging**
